---
- block:

  - name: 'assetfinder : install assetfinder with go get -u github.com/tomnomnom/assetfinder'
    become: yes
    become_user: "{{ user_name }}"
    shell: go get -u github.com/tomnomnom/assetfinder
    args:
        chdir: /home/{{ user_name }}/

  - name: 'assetfinder : add bash alias fo assetfinder'
    become: yes
    become_user: "{{ user_name }}"
    lineinfile: 
        path: /home/{{ user_name }}/.bashrc
        line: alias assetfinder='/home/{{ user_name }}/go/bin/assetfinder'

  - name: 'assetfinder : source bash for bash alias'
    become: yes
    become_user: "{{ user_name }}"
    shell: /bin/bash -ic 'source /home/{{ user_name | quote }}/.bashrc'

  tags:
    - recon
    - assetfinder