---

- block:

  - name: 'dnsgen : Checkout dnsgen Git repository'
    git: 
      repo: https://github.com/ProjectAnte/dnsgen.git
      dest: /home/{{ user_name }}/dnsgen
    
  - name: 'dnsgen : create virtual enviroment for dnsgen'
    shell: python3 -m venv .dnsgen
    args:
      chdir: /home/{{ user_name }}/dnsgen

  - name: 'dnsgen : activate virtual enviroment for dnsgen and install wheel python library'
    shell: /bin/bash -ic 'source .dnsgen/bin/activate; pip3 install wheel'
    args:
      chdir: /home/{{ user_name }}/dnsgen
            
  - name: 'dnsgen : activate virtual enviroment for dnsgen and install requirements'
    shell: /bin/bash -ic 'source .dnsgen/bin/activate; pip3 install -r requirements.txt'
    args:
      chdir: /home/{{ user_name }}/dnsgen

  - name: 'dnsgen : activate virtual enviroment for dnsgen and install requirements'
    shell: /bin/bash -ic 'python3 setup.py install'
    args:
      chdir: /home/{{ user_name }}/dnsgen
    
   tags:
     - recon
     - dnsgen