---
- block:
  
  - name: 'gobuster : clone repository'
    git:
      dest: /home/{{ user_name }}/gobuster
      force: yes
      repo: https://github.com/OJ/gobuster.git

  - name: 'gobuster : exec go get'
    shell: '/bin/bash -lc "/usr/local/go/bin/go get"'
    args:
      chdir: /home/{{ user_name }}/gobuster

  - name: 'gobuster : exec go build'
    shell: '/bin/bash -lc "/usr/local/go/bin/go build"'
    args:
      chdir: /home/{{ user_name }}/gobuster

  - name: 'gobuster : install'
    copy:
      dest: /usr/local/bin/gobuster
      mode: 0775
      remote_src: yes
      src: /home/{{ user_name }}/gobuster

  - name: 'gobuster : cleanup build fragments'
    file:
      dest: '{{ item }}'
      state: absent
    with_items:
      - /home/{{ user_name }}/gobuster
      - /root/.go/bin/gobuster

  tags:
    - recon 
    - gobuster
