---
- block:

  - name: 'pythonTools : install python3 and required dependacies'
    become: true
    apt:
      update_cache: yes
      name:
        - python3-pip
        - python3-dnspython
        - pv 
        - libcurl4-openssl-dev
        - build-essential 
        - libssl-dev 
        - libffi-dev 
        - python-dev

  - name: 'pythonTools : install virtualenv and other python libraries for python3'
    pip:
      name: virtualenv, virtualenvwrapper, jsbeautifier, requests
      executable: pip3
    
  - name: 'pythonTools :clone repos into /opt'
    become: yes
    git:
      repo: "https://{{ item.repo }}.git"
      dest: "/opt/{{ item.dest }}"
    with_items:
      - { repo: 'github.com/x90skysn3k/brutespray', dest: 'brutespray' }
      - { repo: 'github.com/D4Vinci/CWFF', dest: 'CWFF' }
      - { repo: 'github.com/devanshbatham/FavFreak', dest: 'FavFreak' }
      - { repo: 'github.com/nsonaniya2010/SubDomainizer', dest: 'SubDomainizer' }
      - { repo: 'github.com/devanshbatham/ParamSpider', dest: 'ParamSpider' }
      - { repo: 'github.com/d3mondev/puredns', dest: 'puredns' }
      - { repo: 'github.com/m4ll0k/SecretFinder', dest: 'SecretFinder' }
      - { repo: 'github.com/dariusztytko/words-scraper', dest: 'words-scraper' }
      - { repo: 'github.com/SpiderLabs/HostHunter', dest: 'HostHunter' }
      - { repo: 'github.com/ProjectAnte/dnsgen', dest: 'dnsgen' }
      - { repo: 'github.com/xmendez/wfuzz', dest: 'wfuzz' }
      - { repo: 'github.com/codingo/Interlace', dest: 'Interlace' }
      - { repo: 'github.com/s0md3v/Arjun', dest: 'Arjun' }
      - { repo: 'github.com/securing/DumpsterDiver', dest: 'DumpsterDiver' }
      - { repo: 'github.com/techgaun/github-dorks', dest: 'github-dorks' }

  - name: 'pythonTools : change file permissions of pythonTools in /opt directory'
    become: yes 
    file: 
      path: "{{ item }}"
      recurse: yes
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
    with_items:
      - "/opt/brutespray"
      - "/opt/CWFF"
      - "/opt/FavFreak"
      - "/opt/SubDomainizer"
      - "/opt/ParamSpider"
      - "/opt/puredns"
      - "/opt/SecretFinder"
      - "/opt/words-scraper"
      - "/opt/HostHunter"
      - "/opt/dnsgen"
      - "/opt/wfuzz"
      - "/opt/Interlace"
      - "/opt/Arjun"
      - "/opt/DumpsterDiver"
      - "/opt/github-dorks"

  - name: 'pythonTools : create virtual enviroments for pythonTools'
    become: yes
    become_user: "{{ user_name }}"
    shell: virtualenv -p /usr/bin/python3 .
    args:
      chdir: "{{ item }}"
    with_items:
      - "/opt/brutespray"
      - "/opt/CWFF"
      - "/opt/FavFreak"
      - "/opt/SubDomainizer"
      - "/opt/ParamSpider"
      - "/opt/puredns"
      - "/opt/SecretFinder"
      - "/opt/words-scraper"
      - "/opt/HostHunter"
      - "/opt/dnsgen"
      - "/opt/wfuzz"
      - "/opt/Interlace"
      - "/opt/Arjun"
      - "/opt/DumpsterDiver"
      - "/opt/github-dorks"

  - name: 'pythonTools : install miscellaneous python libraries'
    become: yes
    become_user: "{{ user_name }}"
    shell: /bin/bash -ic 'source ./; pip3 install {{ item.library }}'
    args:
      chdir: /opt/{{ item.dir }}
    loop:
      - { dir: 'CWFF', library: 'requests' }
      - { dir: 'FavFreak', library: 'mmh3' }

  - name: 'pythonTools : run python3 setup.py install on selected pythonTools'
    become: yes
    become_user: "{{ user_name }}"
    shell: /bin/bash -ic 'source ./; python3 setup.py install'
    args: 
      chdir: "{{ item }}"
    with_items:
      - "/opt/dnsgen"
      - "/opt/wfuzz"
      - "/opt/Interlace"

  - name: 'pythonTools : install python tools with requirements.txt'
    become: yes
    become_user: "{{ user_name }}"
    shell: /bin/bash -ic 'source ./bin/activate; pip3 install -r requirements.txt'
    args:
      chdir: "{{ item }}"
    with_items:
      - "/opt/brutespray"
      - "/opt/CWFF"
      - "/opt/FavFreak"
      - "/opt/SubDomainizer"
      - "/opt/ParamSpider"
      - "/opt/puredns"
      - "/opt/SecretFinder"
      - "/opt/words-scraper"
      - "/opt/HostHunter"
      - "/opt/dnsgen"
      - "/opt/DumpsterDiver"
      - "/opt/github-dorks"
     
  - name: 'pythonTools : copy startup scripts to /usr/local/bin'
    become: true
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: '0755'
    loop:
      - {src: 'templates/brutespray.j2', dest: '/usr/local/bin/brutespray'}
      - {src: 'templates/cwff.j2', dest: '/usr/local/bin/cwff'}
      - {src: 'templates/favfreak.j2', dest: '/usr/local/bin/favfreak'}
      - {src: 'templates/subdomainizer.j2', dest: '/usr/local/bin/subdomainizer'}
      - {src: 'templates/paramspider.j2', dest: '/usr/local/bin/paramspider'}
      - {src: 'templates/puredns.j2', dest: '/usr/local/bin/puredns'}
      - {src: 'templates/SecretFinder.j2', dest: '/usr/local/bin/SecretFinder'}
      - {src: 'templates/words-scraper.j2', dest: '/usr/local/bin/words-scraper'}
      - {src: 'templates/dnsgen.j2', dest: '/usr/local/bin/dnsgen'}
      - {src: 'templates/wfuzz.j2', dest: '/usr/local/bin/wfuzz'}
      - {src: 'templates/ajurn.j2', dest: '/usr/local/bin/ajurn'}
      - {src: 'templates/DumpsterDiver.j2', dest: '/usr/local/bin/DumpsterDiver'}
      - {src: 'templates/github-dork.j2', dest: '/usr/local/bin/github-dork'}

  tags:
    - recon
    - pythonTools

          
