---
- block:

  - name: 'Secretfinder : Checkout secretfinder Git repository'
    git: 
      repo: https://github.com/m4ll0k/SecretFinder.git
      dest: /home/{{ user_name }}/SecretFinder

  - name: 'SecretFinder : create virtual enviroment for SecretFinder'
    shell: python3 -m venv .SecretFinder
    args:
      chdir: /home/{{ user_name }}/SecretFinder
              
  - name: 'SecretFinder : activate virtual enviroment for SecretFinder and install requirements'
    shell: /bin/bash -ic 'source .SecretFinder/bin/activate; pip3 install -r requirements.txt'
    args:
      chdir: /home/{{ user_name }}/SecretFinder

  tags:
    - recon
    - secretfinder 