---
- block:

  - name: 'trufflehog : Checkout TruffleHog Git repository'
    git: 
      repo: https://github.com/dxa4481/truffleHog.git 
      dest: /home/{{ user_name }}/truffleHog

  - name: 'truffleHog : create virtual enviroment for truffleHog'
    shell: python3 -m venv .truffleHog
    args:
      chdir: /home/{{ user_name }}/truffleHog
                
  - name: 'truffleHog : activate virtual enviroment for truffleHog and install requirements'
    shell: /bin/bash -ic 'source .truffleHog/bin/activate; pip3 install -r requirements.txt'
    args:
      chdir: /home/{{ user_name }}/truffleHog

  tags:
    - recon
    - trufflehog 

  

  