---
- block:

  - name: 'wordscrapper : checkout wordsscraper repo'
    git:
      repo: https://github.com/dariusztytko/words-scraper.git
      dest: /home/{{ user_name }}/words-scraper

  - name: 'words-scraper : create virtual enviroment for words-scraper'
    shell: python3 -m venv .words-scraper
    args:
      chdir: /home/{{ user_name }}/words-scraper
                  
  - name: 'words-scraper : activate virtual enviroment for words-scraper and install requirements'
    shell: /bin/bash -ic 'source .words-scraper/bin/activate; pip3 install -r requirements.txt'
    args:
      chdir: /home/{{ user_name }}/words-scraper

  tags:
    - recon
    - wordscrapper