---
- include: cookie-monster.yml tags=web,cookie-monster
- include: nikto.yml tags=web,nikto
- include: sqlmap.yml tags=web,sqlmap
- include: wfuzz.yml tags=web,wfuzz
- include: wpscan.yml tags=web,wpscan
- include: wpxf.yml tags=web,wpxf
#- include: metasploit.yml tags=web,metasploit
- include: searchsploit.yml tags=web,searchsploit,exploitdb


