---
- block:

  - name: 'nikto : install dependencies'
    apt:
      name:
        - libnet-ssleay-perl
        - libwhisker2-perl
        - perl-openssl-defaults
      state: present
      update_cache: yes

  - name: 'nikto : clone repository'
    become: yes
    git:
      repo: https://github.com/sullo/nikto.git
      dest: /opt/nikto
      
  - name: 'nitko : change premissions for /opt/nitko'
    become: yes
    file: 
      path: /opt/nikto
      recurse: yes
      owner: "{{ user_name }}"
      group: "{{ user_name }}"

  - name: 'nikto : install launcher'
    become: yes
    template:
      src: templates/nikto.j2
      dest: /usr/local/bin/nikto
      owner: "{{ user_name }}"
      group: "{{ user_name }}"
      mode: '0755'
      
  tags:
    - web
    - nikto
