---
- block:
  - name: 'docker : Add Docker apt key'
    become: yes 
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      state: present
    ignore_errors: true

  - name: 'docker : Add Docker repo'
    become: yes
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable" 
      update_cache: yes

  - name: 'docker : update repositories'
    become: yes
    shell: "apt-get -y update"
    register: update  

  - debug: var=update

  - name: 'docker : Install Docker apt package'
    apt:
      pkg: docker-ce
      state: latest
      update_cache: yes
    become: yes

  - name: 'docker : Ensure Docker service is installed and restarted'
    become: yes
    service:
      name: docker
      state: restarted
      enabled: yes

  - name: 'docker : add non root user to docker group.'
    become: yes
    user:
      name: "{{ user_name }}"
      groups: docker
      append: yes
      
  tags:
  - common
  - docker 
